events {}

http {
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    client_body_temp_path /var/tmp/nginx/client_body;
    proxy_temp_path /var/tmp/nginx/proxy;
    fastcgi_temp_path /var/tmp/nginx/fastcgi;

    server {
        listen 8080;
        root /var/www/html;
        index index.html;
    }
}
